# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
  # Test 環境を指定したジョブ
  for_test_env:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Test
    steps:
      - name: Hello
        run: echo Hello from test env. ${{ secrets.MESSAGE }}
